<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BenchmarkDotNet" Version="0.15.8" />
    <PackageVersion Include="CSharpTest.BPlusTree" Version="0.0.14" />
    <PackageVersion Include="MemoryPack" Version="1.21.4" />
    <PackageVersion Include="MessagePack" Version="3.1.4" />
    <PackageVersion Include="System.IO.Hashing" Version="10.0.8" />
    <PackageVersion Include="MSTest" Version="4.2.2" />
    <PackageVersion Include="Umbraco.CSharpTest.Net.Collections" Version="15.0.0" />
  </ItemGroup>
</Project>