name: Release

on: 
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Upload Release
      uses: ncipollo/release-action@v1.20.0    
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
