name: ReleaseMessagePack

on: 
  push:
    tags:
      - "msp*.*.*"

permissions:
  contents: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0.x
    - name: Set VERSION variable from tag
      run: echo "VERSION=${GITHUB_REF/refs\/tags\/msp/}" >> $GITHUB_ENV
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack
      run: dotnet pack ./src/CSharpTest.BPlusTree.MessagePack/CSharpTest.BPlusTree.MessagePack.csproj --no-build --configuration Release -p:PackageVersion=${VERSION}   
    - name: NuGet login (OIDC → temp API key)
      uses: NuGet/login@v1
      id: login
      with:
        user: ${{ secrets.NUGET_USER }}
    - name: push to NuGet
      shell: pwsh
      run: |
        Get-ChildItem src/CSharpTest.BPlusTree.MessagePack/bin/Release -Filter *.nupkg | ForEach-Object {
          dotnet nuget push $_.FullName `
            --api-key "${{ steps.login.outputs.NUGET_API_KEY }}" `
            --source https://api.nuget.org/v3/index.json
        }
